
[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.12.0"

[[constraint]]
  name = "github.com/uber/jaeger-lib"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
